### ISSUE TITLE
oaisim-base build fail!

### ISSUE THREAD

**Issue by manoj1919** [baleeiro17/OAISIMwithdocker#7]
Hi There,
I am trying to build your docker image. free5gc image was built successfully But I am getting the following error while trying to build oaisim-base.
Please help.

nagamanoj_dolcera@Manojs-Macbook-pro oaisim-base % sudo docker build -t oaisim-base .
Password:
[+] Building 50.6s (6/7)                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                0.0s
 => => transferring dockerfile: 269B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                   0.0s
 => => transferring context: 2B                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                     2.8s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                       0.0s
 => CACHED [1/3] FROM docker.io/library/ubuntu:18.04@sha256:fd25e706f3dea2a5ff705dbc3353cf37f08307798f3e360a13e9385840f73fb3        0.0s
 => ERROR [2/3] RUN apt-get update && apt-get install -y git vim nano net-tools cmake g++ kmod linux-image-$(uname -r) linux-head  47.7s
------                                                                                                                                   
 > [2/3] RUN apt-get update && apt-get install -y git vim nano net-tools cmake g++ kmod linux-image-$(uname -r) linux-headers-$(uname -r) sudo:                                                                                                                                   
#5 0.624 Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]                                                                
#5 0.626 Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                     
#5 1.247 Get:3 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1372 kB]                                       
#5 1.441 Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
#5 1.719 Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
#5 2.035 Get:6 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
#5 2.431 Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
#5 4.467 Get:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [15.3 kB]
#5 4.492 Get:9 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1816 kB]
#5 5.525 Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
#5 8.814 Get:11 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [237 kB]
#5 32.82 Get:12 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
#5 32.84 Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2136 kB]
#5 38.55 Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [53.8 kB]
#5 38.68 Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [266 kB]
#5 39.30 Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2244 kB]
#5 44.55 Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
#5 44.57 Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
#5 44.73 Fetched 21.5 MB in 44s (485 kB/s)
#5 44.73 Reading package lists...
#5 46.04 Reading package lists...
#5 47.17 Building dependency tree...
#5 47.36 Reading state information...
#5 47.59 E: Unable to locate package linux-image-4.19.121-linuxkit
#5 47.59 E: Couldn't find any package by glob 'linux-image-4.19.121-linuxkit'
#5 47.59 E: Couldn't find any package by regex 'linux-image-4.19.121-linuxkit'
#5 47.59 E: Unable to locate package linux-headers-4.19.121-linuxkit
#5 47.59 E: Couldn't find any package by glob 'linux-headers-4.19.121-linuxkit'
#5 47.59 E: Couldn't find any package by regex 'linux-headers-4.19.121-linuxkit'
------
executor failed running [/bin/sh -c apt-get update && apt-get install -y git vim nano net-tools cmake g++ kmod linux-image-$(uname -r) linux-headers-$(uname -r) sudo]: exit code: 100

**Comment by baleeiro17** [comment]
Hi, please check this tutorial that we developed for NetSoft https://www.youtube.com/watch?v=ZZZ8UjgyWn4. It is the same environment. Or you can check this simulator https://github.com/my5G/my5G-RANTester for UEs and GNBs that using NGAP/NAS protocol.

If you have some questions let me know.
